name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Code
        run: npm run build

      - name: Copy Firebase Assets
        run: node copyAssets.js

      - name: Restart PM2 Service
        run: |
          pm2 restart onboarding-backend || pm2 start dist/server.js --name "onboarding-backend"
