name: Deploy Onboarding Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted # <-- This tells GitHub to run the build directly on your server

    steps:
    - name: Pull and Build
      run: |
        cd ~/Onboarding-backend
        git checkout main
        git pull origin main
        npm install
        npm run build
        pm2 restart onboarding-backend
